### ISSUE TITLE
The extension is not working well on my remote SSH

### ISSUE THREAD

**Issue by chrisypmail** [splunk/vscode-extension-splunk#9] opened 2020-02-15 16:36 UTC
remote linux is ubuntu 16 with Splunk v8.0 on top of my vmware environment

Local vscode 1.41.1 on my mac v10.13.6

splunk Extension 2.0 installed in my SSH environment.
<img width="253" alt="image" src="https://user-images.githubusercontent.com/43565735/74591500-96290600-5053-11ea-87ba-e11189881f66.png">

SSH is using the "splunk" acount on remote system without admin permission. 

It looks part of the extension function works, as this conf file icon can be displayed. And, I can select the file type: splunk con file
<img width="124" alt="image" src="https://user-images.githubusercontent.com/43565735/74591552-d25c6680-5053-11ea-831b-371c20046463.png">

However, no conf formatting is working there. I was using the default 8.0 spec of the extension. 

And, when I try to refresh the saved searches, this error showed up
<img width="453" alt="image" src="https://user-images.githubusercontent.com/43565735/74591580-fae46080-5053-11ea-86b7-f5b3dd704220.png">

I reloaded the window, the issue was still the same. 

settings.json is pretty simple, just the token and trim space one: 
<img width="523" alt="image" src="https://user-images.githubusercontent.com/43565735/74591611-4eef4500-5054-11ea-8070-fb28c69c5bc4.png">

anything wrong here?

**Comment by JasonConger** [comment] 2020-02-16 23:01
Duplicate of #3 
We are removing the Remote SSH dependency in an upcoming release https://github.com/splunk/vscode-extension-splunk/tree/develop

**Comment by JasonConger** [comment] 2020-03-13 22:35
Resolved in version 0.2.2

**Closed by JasonConger** 2020-03-13 22:35 UTC
